### PR TITLE
Accessibility improvement

### PR DESCRIPTION
**Pull request by Ahsan12356**
In this milestone, I improved the accessibility of my portfolio website project.

- Page Titles - no issues found
- Images alternatives - no issues found
- Text Headings - no issues found
- Color Contrast - [#c35000](https://github.com/Ahsan12356/portfolio/blob/f5fa17240ae45546eaa427fb03540df553685ae1/css/style.css#L307)
- Resize - no issues found
- Interaction - no issues found
- moving contents - no issues found
- Basic Structure of the page - no issues found

### CODE REVIEW

**Review by Santiago220991 — CHANGES_REQUESTED** [review]
Hi @Ahsan12356, 
I'm Santiago your reviewer for this PR. :wave: :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: No linter errors.

## Required Changes ♻️
- Please include a report in your PR summary according to the requirements to the project.
image

- Kindly make sure that your project fulfills the requirements of Contrast ratio ("color contrast"): :eyes: :eyes:  There are 2 issues about this please check the image below and kindly fix this. :pray: :pray:  You can use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help to check the color contrast of the project.

image


image



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ichala — CHANGES_REQUESTED** [review]
Hi @Ahsan12356 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

-  Changes Implemented✔️ 



 ## Required Changes ♻️


- [x] 🛑 You have some conflicts that need to be resolved , kindly resolve it
image

## Optional suggestions

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ahsan12356** [comment]
@ichala I have implemented the changes, and now this branch has no conflicts with the base branch.

**Review by levy002 — APPROVED** [review]
### Hello @Ahsan12356 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
